[package]
name = "mswebrtc"
version = "0.1.0"
edition = "2021"

[lib]
name = "mswebrtc"
crate-type = ["staticlib"]

[dependencies]

[build-dependencies]
cbindgen = "0.12"
uuid = {version="1.16", features=["v4"]}
