name: Build LibMultiSense

on:
  push:
    branches:
      - master
  release:
  pull_request:
    branches:
      - master

jobs:
  #
  # Ubuntu
  #

  # Build modern API on modern Ubuntu versions for various configurations.
  build-ubuntu-modern-api:
    name: "${{ matrix.ubuntu_version }}, modern API, ${{ matrix.compiler }}, ${{ matrix.build_type }}, ${{ matrix.shared_libs && 'shared' || 'static' }}, ${{ matrix.minimal && 'minimal' || 'full' }}, python"
    strategy:
      fail-fast: false
      matrix:
        ubuntu_version: [ubuntu-24.04]
        compiler: [gcc]
        build_type: [Release, Debug]
        shared_libs: [true, false]
        minimal: [true, false]
        include:
          # Build Clang in representative full shared configurations.
          - ubuntu_version: ubuntu-24.04
            compiler: clang
            build_type: Release
            shared_libs: true
            minimal: false

          - ubuntu_version: ubuntu-24.04
            compiler: clang
            build_type: Debug
            shared_libs: true
            minimal: false

    uses: ./.github/workflows/build-ubuntu.yml
    with:
      ubuntu_version: ${{ matrix.ubuntu_version }}
      compiler: ${{ matrix.compiler }}
      build_type: ${{ matrix.build_type }}
      shared_libs: ${{ matrix.shared_libs }}
      testing: true
      legacy_api: false
      build_json_serialization: ${{ !matrix.minimal }}
      build_opencv: ${{ !matrix.minimal }}
      python_bindings: true
      asan: false
      coverage: false
      upload_artifacts: ${{ matrix.compiler == 'gcc' && matrix.build_type == 'Release' && matrix.shared_libs && !matrix.minimal }}

  # Build modern API on older Ubuntu versions for limited configurations.
  build-ubuntu-modern-api-old-ubuntu:
    name: "${{ matrix.ubuntu_version }}, modern API, gcc, Release, shared, full, python"
    strategy:
      fail-fast: false
      matrix:
        ubuntu_version: [ubuntu-22.04]

    uses: ./.github/workflows/build-ubuntu.yml
    with:
      ubuntu_version: ${{ matrix.ubuntu_version }}
      compiler: gcc
      build_type: Release
      shared_libs: true
      testing: true
      legacy_api: false
      build_json_serialization: true
      build_opencv: true
      python_bindings: true
      asan: false
      coverage: false
      upload_artifacts: false

  # Build legacy API in limited configurations.
  build-ubuntu-legacy-api:
    name: "${{ matrix.ubuntu_version }}, legacy API, gcc, Release, ${{ matrix.shared_libs && 'shared' || 'static' }}, full, no-python"
    strategy:
      fail-fast: false
      matrix:
        shared_libs: [true, false]

    uses: ./.github/workflows/build-ubuntu.yml
    with:
      ubuntu_version: ubuntu-24.04
      compiler: gcc
      build_type: Release
      shared_libs: ${{ matrix.shared_libs }}
      testing: true
      legacy_api: true
      build_json_serialization: true
      build_opencv: true
      python_bindings: false # No Python bindings for legacy API.
      asan: false
      coverage: false
      upload_artifacts: false

  # Build code coverage.
  build-ubuntu-coverage:
    name: "${{ matrix.ubuntu_version }}, coverage, gcc, Debug, shared, full, no-python"
    uses: ./.github/workflows/build-ubuntu.yml
    with:
      ubuntu_version: ubuntu-24.04
      compiler: gcc
      build_type: Debug
      shared_libs: true
      testing: true
      legacy_api: false
      build_json_serialization: true
      build_opencv: true
      python_bindings: false
      asan: false
      coverage: true
      upload_artifacts: false
    secrets: inherit

  # Build with address sanitizer.
  build-ubuntu-asan:
    name: "${{ matrix.ubuntu_version }}, ASan, gcc, Debug, shared, full, no-python"
    uses: ./.github/workflows/build-ubuntu.yml
    with:
      ubuntu_version: ubuntu-24.04
      compiler: gcc
      build_type: Debug
      shared_libs: true
      testing: true
      legacy_api: false
      build_json_serialization: true
      build_opencv: true
      python_bindings: false
      asan: true
      coverage: false
      upload_artifacts: false

  #
  # macOS
  #

  # Build only the modern API in various configurations.
  build-macos:
    name: "${{ matrix.macos_version }}, modern API, ${{ matrix.compiler }}, ${{ matrix.build_type }}, ${{ matrix.shared_libs && 'shared' || 'static' }}, full, python"
    strategy:
      fail-fast: false
      matrix:
        macos_version: [macos-latest]
        compiler: [apple-clang, brew-llvm]
        build_type: [Release, Debug]
        shared_libs: [true]
        legacy_api: [false]
        build_json_serialization: [true]
        build_opencv: [true]
        python_bindings: [true]
        include:
          # Build one representative static macOS configuration.
          - macos_version: macos-latest
            compiler: apple-clang
            build_type: Release
            shared_libs: false
            legacy_api: false
            build_json_serialization: true
            build_opencv: true
            python_bindings: true

    uses: ./.github/workflows/build-macos.yml
    secrets: inherit
    with:
      macos_version: ${{ matrix.macos_version }}
      compiler: ${{ matrix.compiler }}
      build_type: ${{ matrix.build_type }}
      shared_libs: ${{ matrix.shared_libs }}
      testing: true
      legacy_api: ${{ matrix.legacy_api }}
      build_json_serialization: ${{ matrix.build_json_serialization }}
      build_opencv: ${{ matrix.build_opencv }}
      python_bindings: ${{ matrix.python_bindings }}
      upload_artifacts: ${{ matrix.build_type == 'Release' && matrix.shared_libs }}

  #
  # Windows
  #

  # Build only the modern API in various configurations.
  build-windows:
    name: "${{ matrix.windows_version }}, modern API, ${{ matrix.compiler }}, ${{ matrix.build_type }}, ${{ matrix.shared_libs && 'shared' || 'static' }}, full, python"
    strategy:
      fail-fast: false
      matrix:
        windows_version: [windows-2022]
        compiler: [msvc]
        build_type: [Release, Debug]
        shared_libs: [true]
        legacy_api: [false]
        build_json_serialization: [true]
        build_opencv: [true]
        python_bindings: [true]
        include:
          # Build Clang in representative full shared configurations.
          - windows_version: windows-2022
            compiler: clang
            build_type: Release
            shared_libs: true
            legacy_api: false
            build_json_serialization: true
            build_opencv: true
            python_bindings: true

          - windows_version: windows-2022
            compiler: clang
            build_type: Debug
            shared_libs: true
            legacy_api: false
            build_json_serialization: true
            build_opencv: true
            python_bindings: true

          # Build one representative static Windows configuration.
          - windows_version: windows-2022
            compiler: msvc
            build_type: Release
            shared_libs: false
            legacy_api: false
            build_json_serialization: true
            build_opencv: true
            python_bindings: true

    uses: ./.github/workflows/build-windows.yml
    with:
      windows_version: ${{ matrix.windows_version }}
      compiler: ${{ matrix.compiler }}
      build_type: ${{ matrix.build_type }}
      shared_libs: ${{ matrix.shared_libs }}
      legacy_api: ${{ matrix.legacy_api }}
      build_json_serialization: ${{ matrix.build_json_serialization }}
      build_opencv: ${{ matrix.build_opencv }}
      python_bindings: ${{ matrix.python_bindings }}
      upload_artifacts: ${{ matrix.build_type == 'Release' && matrix.shared_libs }}

  build-android:
    name: Build on Android
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Release
        run: |
          cmake -B build-android -S . \
            -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_LATEST_HOME/build/cmake/android.toolchain.cmake \
            -DANDROID_ABI=arm64-v8a \
            -DANDROID_PLATFORM=android-24 \
            -DBUILD_TESTS=OFF \
            -DBUILD_PYTHON_BINDINGS=OFF \
            -DBUILD_LEGACY_API=OFF \
            -DCMAKE_BUILD_TYPE=Release

          cmake --build build-android -j "$(nproc)"

