name: Build LibMultiSense on Ubuntu

on:
  workflow_call:
    inputs:
      ubuntu_version:
        type: string
        default: ubuntu-latest
        description: A valid Ubuntu runner name.
      compiler:
        type: string
        default: gcc
        description: One of {gcc, clang}.
      build_type:
        type: string
        default: Release
        description: One of {Release, Debug}.
      shared_libs:
        type: boolean
        default: true
        description: Whether to build the shared libraries.
      testing:
        type: boolean
        default: false
        description: Whether to enable testing.
      legacy_api:
        type: boolean
        default: false
        description: Whether to build the legacy API.
      build_json_serialization:
        type: boolean
        default: false
        description: Whether to build with JSON serialization.
      build_opencv:
        type: boolean
        default: false
        description: Whether to build with OpenCV support.
      python_bindings:
        type: boolean
        default: true
        description: Whether to build the Python bindings.
      asan:
        type: boolean
        default: false
        description: Whether to enable address sanitization.
      coverage:
        type: boolean
        default: false
        description: Whether to enable code coverage.
      upload_artifacts:
        type: boolean
        default: false
        description: Whether to upload artifacts.

jobs:
  build:
    name: "${{ inputs.coverage && 'configure build coverage upload' || inputs.testing && 'configure build test install' || 'configure build install' }}"
    runs-on: ${{ inputs.ubuntu_version }}

    env:
      CC: ${{ inputs.compiler == 'clang' && 'clang' || 'gcc' }}
      CXX: ${{ inputs.compiler == 'clang' && 'clang++' || 'g++' }}
      NAME: ${{ inputs.ubuntu_version }}-${{ inputs.compiler }}-${{ inputs.build_type == 'Release' && 'release' || 'debug' }}-${{ inputs.shared_libs && 'shared' || 'static' }}-${{ inputs.legacy_api && 'legacy' || 'modern' }}-${{ inputs.build_json_serialization && inputs.build_opencv && 'full' || 'minimal' }}-${{ inputs.python_bindings && 'python' || 'nopython' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

        #
        # Install build dependencies
        #

      - name: Install core build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            ninja-build

      - name: Install GCC
        if: inputs.compiler == 'gcc'
        run: |
          sudo apt-get install -y \
            gcc \
            g++

      - name: Install Clang
        if: inputs.compiler == 'clang'
        run: |
          sudo apt-get install -y \
            clang

      - name: Install testing dependencies
        if: inputs.testing
        run: |
          sudo apt-get install -y \
            libgtest-dev

      - name: Install JSON serialization dependencies
        if: inputs.build_json_serialization
        run: |
          sudo apt-get install -y \
            nlohmann-json3-dev

      - name: Install OpenCV dependencies
        if: inputs.build_opencv
        run: |
          sudo apt-get install -y \
            libopencv-dev

      - name: Install Python bindings dependencies
        if: inputs.python_bindings
        run: |
          sudo apt-get install -y \
            pybind11-dev \
            python3-pip \
            python3-venv

      - name: Install code coverage dependencies
        if: inputs.coverage
        run: |
          sudo apt-get install -y \
            lcov

      #
      # Build the library
      #

      - name: Build library
        run: |
          cmake -B build -S . \
            -DCMAKE_C_COMPILER=${{ env.CC }} \
            -DCMAKE_CXX_COMPILER=${{ env.CXX }} \
            -DCMAKE_BUILD_TYPE=${{ inputs.build_type }} \
            -DBUILD_SHARED_LIBS=${{ inputs.shared_libs }} \
            -DBUILD_TESTS=${{ inputs.testing }} \
            -DBUILD_LEGACY_API=${{ inputs.legacy_api }} \
            -DBUILD_JSON_SERIALIZATION=${{ inputs.build_json_serialization }} \
            -DBUILD_OPENCV=${{ inputs.build_opencv }} \
            -DBUILD_PYTHON_BINDINGS=${{ inputs.python_bindings }} \
            -DENABLE_ASAN=${{ inputs.asan }} \
            -DENABLE_COVERAGE=${{ inputs.coverage }} \
            -DCMAKE_INSTALL_PREFIX=install

          cmake --build build -j "$(nproc)"
          if [ "${{ inputs.coverage }}" = "true" ]; then
            cmake --build build --target coverage
          elif [ "${{ inputs.testing }}" = "true" ]; then
            ctest --test-dir build --output-on-failure
          fi
          cmake --install build

      - name: Build pip wheel
        if: inputs.python_bindings
        run: |
          mkdir pip-wheel
          python3 -m venv .venv
          source .venv/bin/activate
          python3 -m pip wheel --wheel-dir pip-wheel .

      #
      # Upload artifacts
      #

      - name: Upload library artifact
        uses: actions/upload-artifact@v7
        if: inputs.upload_artifacts
        with:
          name: install-${{ env.NAME }}
          path: install/

      - name: Upload pip wheel Artifact
        uses: actions/upload-artifact@v7
        if: inputs.upload_artifacts && inputs.python_bindings
        with:
          name: libmultisense-wheel-${{ env.NAME }}
          path: pip-wheel/

      - name: Upload Coverage to Codecov
        if: inputs.coverage
        uses: codecov/codecov-action@v6
        with:
          file: build/coverage_filtered.info
          fail_ci_if_error: false
          token: ${{ secrets.CODECOV_TOKEN }}
